src/object.ts
src/tests/object.test.ts

Avoid cases in `set(…)` where a key starts with an integer (but is not only an integer) being inferred as an array index.
Resolves https://github.com/sodiray/radash/pull/383 and https://github.com/sodiray/radash/issues/357
Thanks @UnKnoWn-Consortium

fix(set): avoid false positive of array index in path

---

src/object.ts
src/tests/object.test.ts

The `shake` function cannot make any guarantees at the type-level about the returned object, so the return type should just be `T`.
Also, its `filter` callback now has a correctly typed `value` parameter.
Resolves https://github.com/sodiray/radash/pull/404
Thanks to @AliubYiero

fix(shake): stop using `Omit` on return type and give `filter` parameter a safer type

---

src/series.ts
src/tests/series.test.ts

Resolves https://github.com/sodiray/radash/pull/272
Thanks to @JacobWeisenburger

fix(series): allow `items` param to be a readonly array

---

docs/typed/is-plain-object.mdx
src/index.ts
src/tests/typed.test.ts
src/typed.ts

Adds `isPlainObject` which returns true for both `{}` and `Object.create(null)`, nothing else.

feat: add `isPlainObject` type guard

---

docs/typed/is-object.mdx
src/object/assign.ts
src/object/keys.ts
src/object/tests/assign.test.ts
src/object/tests/keys.test.ts

Using `isObject` internally is hostile to any use case in need of `Object.create(null)`, so we'll use `isPlainObject` instead.
Affected functions include:
- `assign`
- `crush`
- `keys`
When an object created with `Object.create(null)` is nested in the argument to `assign`, `crush`, or `keys`, it will be treated as if it was created with `{}`. In the case of `assign`, any time such an object is assigned to, the resulting clone of the object will have a null prototype as expected.
Resolves https://github.com/sodiray/radash/issues/409

fix: avoid `isObject` for internal use

---

src/array/intersects.ts
src/array/tests/intersects.test.ts

Allow `intersects`' `identity` parameter to return any value, not just string/number/symbol values.

feat(intersects): let `identity` return any value

---

src/array/tests/unique.test.ts
src/array/unique.ts

Allow `unique`'s `toKey` parameter to return any value, instead of only values that can be identified through a key or those that can be used as keys themselves.
Resolves https://github.com/sodiray/radash/issues/342

feat(unique): let `toKey` return any kind of value

---

src/array/select.ts
src/array/tests/select.test.ts

If the `condition` parameter is undefined, the `mapper` result is checked with `!= null` instead, so `null` and `undefined` results are omitted from the new array.
```ts
const result = select(
[{ a: 1 }, { a: 2 }, { b: 1 }],
(obj) => obj.a,
)
expect(result).toEqual([1, 2])
```
Resolves https://github.com/sodiray/radash/issues/269

feat(select): let `condition` be undefined

---

src/array/fork.ts

Array fork function is awful at performance. This is a fix.
There is no breaking changes, just performance improvements.
New implementation is ~90x faster ([Benchmark](https://perf.link/#eyJpZCI6ImxzY284ZTU4M2hhIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBbLi4uQXJyYXkoMTAwMCkua2V5cygpXTtcblxuZnVuY3Rpb24gZm9yayhsaXN0LCBjb25kaXRpb24pIHtcbiAgaWYgKCFsaXN0KSByZXR1cm4gW1tdLCBbXV1cbiAgcmV0dXJuIGxpc3QucmVkdWNlKFxuICAgIChhY2MsIGl0ZW0pID0%2BIHtcbiAgICAgIGNvbnN0IFthLCBiXSA9IGFjY1xuICAgICAgaWYgKGNvbmRpdGlvbihpdGVtKSkge1xuICAgICAgICByZXR1cm4gW1suLi5hLCBpdGVtXSwgYl1cbiAgICAgIH0gZWxzZSB7XG4gICAgICAgIHJldHVybiBbYSwgWy4uLmIsIGl0ZW1dXVxuICAgICAgfVxuICAgIH0sXG4gICAgW1tdLCBbXV1cbiAgKVxufVxuXG5mdW5jdGlvbiBuZXdfZm9yayhsaXN0LCBjb25kaXRpb24pIHtcbiAgdmFyIHJlc3VsdCA …

Improve fork performance

---

.github/workflows/publish-beta.yml
.vscode/settings.json
package.json
pnpm-lock.yaml
src/array/alphabetical.ts
src/array/boil.ts
src/array/first.ts
src/array/iterate.ts
src/array/last.ts
src/array/merge.ts
src/array/replace.ts
src/array/replaceOrAppend.ts
src/array/select.ts
src/array/sort.ts
src/array/toggle.ts
src/async/tests/retry.test.ts
src/curry/callable.ts
src/curry/debounce.ts
src/curry/partial.ts
src/curry/throttle.ts
src/object/listify.ts
src/series/series.ts
src/string/template.ts
src/string/trim.ts
tsconfig.json

> [!TIP]
The new `--isolatedDeclarations` flag in TypeScript enforces explicit types for module boundaries. I think this is a good fit for Radashi for two reasons:
1. Biome doesn't support this yet.
2. Currently, we use `--allow-slow-types` when publishing to JSR. This lets us avoid that.
Depends on https://github.com/radashi-org/radashi/pull/38

chore: upgrade typescript and use --isolatedDeclarations

---

src/string/template.ts

> [!TIP]
Haven't benchmarked this yet, but it's a lot faster in theory. The question is whether the extra lines are worth it, which depends on how people are using the `template` function most often. For small strings, the perf gains of this PR are probably negligible.

chore(perf): make `template` faster

---

docs/number/round.mdx
src/mod.ts
src/number/round.ts
src/number/tests/round.test.ts

> [!TIP]
The round function is designed to round a given number to a specified precision. 
https://github.com/sodiray/radash/issues/61
Feature
No

feat: add `round` function

---

.github/contributing.md
package.json
scripts/add-function.sh

> [!TIP]
Contributors can now run `pnpm add-function` to automatically set up the files required for adding a new function to Radashi!
**Note:** You will need to manually export your function from `src/mod.ts` before you can use it.
```sh
pnpm add-function <group-name>/<function-name>
pnpm add-function array/filter
```
**Details:**
- If you accidentally type a group name that doesn't exist, the script will ask you if that was intentional.
- It creates a file in the following directories: `src`, `tests`, `docs`, and `benchmarks`
- It asks you for a short description of the function, which is displayed on the official …

chore: add `pnpm add-function` command

---

src/array/cluster.ts

> [!TIP]
The previous implementation used `new Array()`, filled it with nulls, then mapped it. That's two array allocations and two enumerations (the fill and the map), although the `fill` was probably very fast.
Either way, this PR avoids the `map` altogether and the code is just as tiny.
No

perf(cluster): avoid an array allocation

---

benchmarks/array/unzip.bench.ts
docs/array/unzip.mdx
src/array/unzip.ts
src/array/zip.ts
src/mod.ts
tests/array/unzip.test.ts

> [!TIP]
The opposite of `zip`. In fact, `zip` uses `unzip` internally.
I also took this as an opportunity to improve the performance of `zip`, avoiding the `fill` and `map` calls, similar to what I did in #63.
No

feat: add `unzip` function

---

src/array/replace.ts

> [!TIP]
Generally speaking, a `splice` should be better performance than allocating 2 arrays that will need to be garbage collected. Not sure how well the benchmarks detect GC-related perf issues, though.
*edit:* @Minhir realized we could use basic assignment instead of `splice`. 🎉 
No

perf(replace): avoid creating 2 intermediate arrays

---

0001-feat-array-support-iterables-in-some-array-functions.patch
src/array/replaceOrAppend.ts

> [!TIP]
Generally speaking, a `splice` should be better performance than allocating 2 arrays that will need to be garbage collected. Not sure how well the benchmarks detect GC-related perf issues, though.
*edit:* @Minhir realized we could use basic assignment instead of `splice`. 🎉 
No

perf(replaceOrAppend): avoid creating 2 intermediate arrays

---

tests/async/parallel.test.ts
tests/async/retry.test.ts
tests/async/sleep.test.ts
tests/curry/debounce.test.ts
tests/curry/memo.test.ts
tests/curry/throttle.test.ts

> [!TIP]
Speeds up test runs by ~5-10 seconds by using [Vitest fake timers](https://vitest.dev/api/vi.html#vi-usefaketimers) to simulate the passage of time.
Before:
After:
Resolves https://github.com/radashi-org/radashi/issues/21
No

test: use fake timers in tests

---

src/number/toFloat.ts
src/number/toInt.ts
tests/number/toFloat.test.ts
tests/number/toInt.test.ts

- fix(toInt): avoid throwing on symbol input
- fix(toFloat): avoid throwing on symbol input
- chore: simplify tests
> [!TIP]
Both `toInt` and `toFloat` should handle any possible input, including symbols. They were throwing on symbols, so I've fixed it. I've also cleaned up the implementations beyond that. I'm also using TypeScript overload syntax to prevent a weird return type of `number | number` and it now allows any value type to be the default value.
No

fix: toInt and toFloat symbol input

---

src/async/all.ts
src/mod.ts
src/typed/isArray.ts
src/types.ts
tests/typed/isArray.test-d.ts

> [!TIP]
This PR adds “type tests” for `isArray`, showcasing its utility. See the `tests/typed/isArray.test-d.ts` file. Notably, our `isArray` utility actually works with readonly arrays, while `Array.isArray` does not.
In addition, it improves the return type when the input value is typed `unknown`. It now returns a mutable array type, instead of a readonly one. I believe this new behavior is the most common expectation of how it should work.
No

fix(types): improve the `isArray` return type for `unknown` input type

---

src/random/shuffle.ts
tests/random/shuffle.test.ts

> [!TIP]
This PR replaces the current implementation of the shuffle function with a more efficient version using the Fisher-Yates algorithm.
**Key changes:**
1. Switched from a functional to an imperative approach for better performance.
2. Implemented Fisher-Yates shuffle algorithm for in-place shuffling.
3. Added option to pass custom random function, defaulting to Radashi's `random` function.
4. Ensured original array is not mutated by creating a copy.
**Performance implications:**
- Improved time complexity from O(n log n) to O(n).
- Reduced memory usage by avoiding creation of intermediate arrays.
- Potentially …

perf(shuffle): use the Fisher-Yates algorithm

---

docs/object/pick.mdx
src/object/pick.ts
tests/object/pick.test.ts

> [!TIP]
```ts
const newObject = pick(object, (value, key, object) => key.startsWith('a'))
```
This brings [lodash.pickBy](https://lodash.com/docs/4.17.15#pickBy) functionality to Radashi.
https://github.com/sodiray/radash/issues/157
https://github.com/sodiray/radash/pull/402
Also fixes https://github.com/sodiray/radash/issues/326, because the array of keys can now be typed `readonly` without complaints from TypeScript.

feat(pick): accept a callback for advanced picking

---

benchmarks/number/lerp.bench.ts
docs/number/lerp.mdx
src/mod.ts
src/number/lerp.ts
tests/number/lerp.test.ts

> [!TIP]
Introduce the `lerp` function for linear interpolation, a common need in frontend JavaScript. This function will be used in the upcoming color-mixing PR.
1. **Does this fit in Radashi?**  
I believe it does. In my years as a frontend dev, I've written my own `lerp` countless times. It's small enough to not be a big deal for Node.js applications using Radashi.
2. **Should it have a better name?**  
I settled on `lerp` since it's the most commonly used name for such a function. I included an "Etymology" section in the docs to hopefully clear up any confusion.
No

feat: add `lerp` function

---

src/array/toggle.ts
tests/array/toggle.test.ts

> [!TIP]
Previously, toggle didn't work with falsy values in array `toggle([1, 2], 0)`.
It could be a breaking change (even if it's clearly bug). I think it should be released together with https://github.com/radashi-org/radashi/pull/70.

fix(toggle): handle falsy input as expected

---

benchmarks/number/clamp.bench.ts
docs/number/clamp.mdx
src/mod.ts
src/number/clamp.ts
tests/number/clamp.test.ts

> [!TIP]
The `clamp` function is like a combination of `Math.min` and `Math.max`. Both the min and max can be nullish, in which case they are ignored.
Resolves https://github.com/lodash/lodash/issues/3139 – When the min is > max, an error is thrown by Radashi.
No
| Status | File | Size |
|---|---|---|
| A | `src/number/clamp.ts` | 146 |

feat: add `clamp` function

---

src/object/assign.ts
tests/object/assign.test.ts

> [!TIP]
Fix `assign` so a nested object can be replaced with null.
See the test case.
https://github.com/sodiray/radash/issues/373
No
| Status | File | Size | Difference (%) |
| M | `src/object/assign.ts` | 431 | -23 (-6%) |

fix(assign): fix overriding a nested object with null

---

src/object/crush.ts
src/types.ts
tests/object/crush.test-d.ts
tests/object/crush.test.ts

Resolves https://github.com/sodiray/radash/issues/365
Resolves #23

fix(crush): fix handling of period-containing property names

---

src/async/AggregateError.ts
tests/async/AggregateError.test.ts
tests/async/AggregateError2.test.ts
tests/tsconfig.json

Implements logic to use a native implementation if available instead of a polyfill.
#75
To create my test, I had to create a separate file because I encountered issues using `vi.stubGlobal` in the same file. I discovered this happens because Vitest uses the same workers per test file. Running tests simultaneously causes conflicts with `globalThis` sharing. More details can be found in this discussion: https://github.com/vitest-dev/vitest/discussions/1741. The workaround I found was to use two files. It’s not ideal, but it works. Any suggestions for a better solution are welcome.
No
_Calculating..._

feat: use native AggregateError if available

---

package.json
pnpm-lock.yaml

I found a way to fix the 10000 ms process problem. 
It appears that the error was contained because in your branch you only updated `vitest` to v2 and not `@vitest/coverage-v8`
#96 
No

chore: upgrade @vitest/coverage-v8 v2

---

src/array/shift.ts

> [!TIP]
Similar to other changes in radashi, I updated the `shift` function to allow readonly arrays as parameter.
No
_Calculating..._

fix(types): let `shift` accept a readonly array type

---

package.json
pnpm-lock.yaml
vitest.config.ts

> [!TIP]
No particular reason to rush this upgrade (I was seeing a “hanging process” issue that prevented Vitest from exiting before a 10 second timeout. But opening this in case someone wants to investigate.
Vitest 1.6.0 --> 2.0.1
No

chore: upgrade to vitest v2

---

docs/curry/throttle.mdx
src/curry/throttle.ts
tests/curry/throttle.test.ts

> [!TIP]
This adds a `trailing` option for `throttle`, which results in the source function being invoked again after `interval` in case any calls were ignored during the throttled period.
This is useful for situations where an observable is frequently changing, and we wish to throttle an observer without missing any updates. 
https://github.com/sodiray/radash/pull/387
No

feat(throttle): add `trailing` option

---

docs/curry/throttle.mdx
src/curry/throttle.ts
tests/curry/throttle.test.ts

> [!TIP]
The `trigger` method lets you skip the throttle queue and invoke the function immediately. This will reset the throttle timeout too.
```ts
const logMessage = (message: string) => {
console.log(`Message: ${message}`)
}
const throttledLog = throttle({ interval: 1000 }, logMessage)
throttledLog('First call')  // Logs immediately
throttledLog('Throttled')   // Doesn't log (throttled)
// Force a log, bypassing the throttle
throttledLog.trigger('Forced log')  // Logs immediately
// Check if it's still throttled
throttledLog.isThrottled()  // => true
```
No
| Status | File | Size | Difference (%) |
| …

feat(throttle): add `trigger` method to ThrottleFunction

---

src/async/AggregateError.ts
src/curry/once.ts
src/typed/isArray.ts
src/typed/isInt.ts

> [!TIP]
Ideally, we could remove all of these workarounds in the future.
https://github.com/evanw/esbuild/issues/2010#issuecomment-1035765782
No
| Status | File | Size | Difference (%) |
| M | `src/async/AggregateError.ts` | 300 [^1337] | +0 (+0%) |
| M | `src/curry/once.ts` | 175 | +25 (+16%) |
| M | `src/typed/isArray.ts` | 45 | +0 (+0%) |
| M | `src/typed/isInt.ts` | 48 | +0 (+0%) |

chore: help esbuild tree-shake with pure annotations

---

src/number/sum.ts
tests/number/sum.test.ts

> [!TIP]
In [a Radash issue](https://github.com/sodiray/radash/issues/419), there was a need to handle a list of boolean values. Therefore, I decided to implement a type adjustment to address this case.
https://github.com/sodiray/radash/issues/419
No
| Status | File | Size |
|---|---|---|

feat(sum): improve type for list of booleans

---

.devcontainer/devcontainer.json

In my daily work, I use Development Containers for all my applications. This approach is also widely adopted by large teams. Development containers allow us to create a Docker environment tailored for development, complete with a pre-configured operating system, dependencies, packages, extensions, and settings. This greatly facilitates the development process.
I have prepared a contribution that integrates development containers into the project. This setup works with both VSCode and IntelliJ, as well as with online code editors like CodeSandbox and GitHub Codespaces. I believe this configuration would add significant value to the project.
- [GitHub Codespaces](https://containers.dev/supporting#github-codespaces)
- [Development Containers Documentation](https://containers.dev/)
1. clone …

chore: setup dev containers

---

scripts/release-notes.sh
scripts/release-notes/README.md
scripts/release-notes/dedent.ts
scripts/release-notes/package.json
scripts/release-notes/pnpm-lock.yaml
scripts/release-notes/release-notes.ts

Generate release notes using `git log -p` output and Anthropic Claude. Before the release notes are saved to file or published to GitHub, you'll have a chance to edit them with whatever editor you have set via `git config --global core.editor <editor>`.
- `ANTHROPIC_API_KEY`
- `GITHUB_TOKEN` (only required if --publish is used)
```sh
scripts/release-notes.sh
scripts/release-notes.sh <commit-ref>
```
```
-o, --output <file>
Write the release notes to a file.
--publish
Publish the release notes to GitHub.
--draft
Publish the release notes as a draft.
--prerelease
Publish the release notes as a prerelease.
```
| Status | File | Size |
|---|---|---|

chore: add script for generating an initial draft of release notes

---

docs/async/withResolvers.mdx
src/async/withResolvers.ts
src/mod.ts
tests/async/withResolvers.test.ts

> [!TIP]
Not sure if that one should be public util or radashi internal one.
No
| Status | File | Size |
|---|---|---|
| A | `src/async/withResolvers.ts` | 114 [^1337] |

feat: add `withResolvers` ponyfill

---

docs/array/toggle.mdx
src/array/toggle.ts
tests/array/toggle.test.ts

It's strange to call `toKey` for an item with different indexes. We can provide `-1` instead and call it only once. 
No
| Status | File | Size | Difference (%) |
| M | `src/array/toggle.ts` | 257 [^1337] | +22 (+9%) |

fix(toggle): use -1 as index for `toKey()` with toggled `item`

---

src/object/assign.ts
src/types.ts
tests/object/assign.test-d.ts
tsconfig.json

> [!TIP]
- Add the `Assign` type, which tries to be as accurate as possible.
- Add the `BuiltInType` utility type as a union type of all built-in types (including DOM-specific and NodeJS-specific types when possible).
- Add the `OptionalKeys` and `RequiredKeys` utility types.
Since there's no built-in way to differentiate a “plain object” type and a custom class instance type, I've added the `CustomClassRegistry` interface. Anyone can extend this in their project by using “declaration merging”:
```ts
class FooBar {
foo: unknown
bar: unknown
}
declare module 'radashi' {
interface CustomClassRegistry {
FooBar: FooBar
}
} …
```

fix(types): make `assign` return type more accurate + add `Assign` type

---

src/types.ts

> [!TIP]
- **Ok**
- `Ok<string>` → `[undefined, string]`
- `Ok<Promise<string>>` → `[undefined, string]`
- **Err**
- `Err` → `[Error, undefined]`
- `Err<unknown>` → `[NonNullable<unknown>, undefined]`
- `Err<Error | string>` → `[Error | string, undefined]`
- **Result**
- `Result<string>` → `Ok<string> | Err`
- `Result<string, TypeError>` → `Ok<string> | Err<TypeError>`
- **ResultPromise**
- `ResultPromise<string>` → `Promise<Ok<string> | Err>`
- `ResultPromise<string, TypeError>` → `Promise<Ok<string> | Err<TypeError>>`
The goal is to keep these types as straight-forward as possible.
- `isResult`: Check if some value is …

feat: add types for Ok/Err/Result/ResultPromise

---

docs/typed/isResult.mdx
src/typed/isResult.ts
src/typed/isResultErr.ts
src/types.ts
tests/typed/isResult.test.ts

> [!TIP]
Fix `isResult` to return true for a `[undefined, undefined]` tuple. This is to handle the case where a function with a possibly undefined return value is wrapped with `tryit`, which may produce such a tuple.
I'm also constraining the `TError` type parameter of Result/Ok/Err so it must be a subtype of the built-in `Error` type. In other words, it no longer allows the error element to be any type. This is necessary to reduce the chance of `isResult` returning a false positive for certain arrays.
*Note: This is a "chore" and not a "fix" because `isResult` hasn't been released yet.*
No
| Status | File | Size …

chore(fix): allow Result tuple to be `[undefined, undefined]`

---

docs/typed/isPromise.mdx
src/async/tryit.ts
src/typed/isPromise.ts
tests/typed/isPromise.test.ts

> [!TIP]
Change the return type from `Promise<any>` to `PromiseLike<unknown>`. This is more representative of the actual check being done.
*Note: This type guard assumes a "then" method is only ever used for promise-like behavior. Please avoid using this function if you can't ensure such a thing.*
Inspired by https://github.com/orgs/radashi-org/discussions/73. This PR does **not** resolve that issue. I still think we need to rename this function to `isPromiseLike`, but that is a breaking change, so it needs its own PR.
No
| Status | File | Size  [^1337] | Difference (%) |
| M | `src/async/tryit.ts` | …

fix(types): align `isPromise` return type with its logic

---

docs/array/flat.mdx
src/array/flat.ts

> [!TIP]
Update the JSDOC and documentation about the function being deprecated.
https://github.com/orgs/radashi-org/discussions/84
Yes
| Status | File | Size  [^1337] | Difference (%) |
| M | `src/array/flat.ts` | 49 | -28 (-36%) |

chore: deprecate `flat`

---

benchmarks/string/pascal.bench.ts
docs/string/pascal.mdx
src/string/pascal.ts
tests/string/pascal.test.ts

> [!TIP]
Fix #176. 
<details>
<summary>Performance details</summary>
<br>
I changed the code suggestion because it degraded performance a bit. After spending some time playing with regular expressions, So far, the best performance I've achieved.
| togle | performance |
| - | -|
|    original code (with error) |   ![image](https://github.com/user-attachments/assets/652e6e79-8532-4830-a008-bfe9ec49236c)   | 
|  [code sujestion](https://github.com/sodiray/radash/issues/292#issue-1667884084)  |  ![image](https://github.com/user-attachments/assets/778b248f-2e2b-49c3-94f2-184e352b6b70) | 
| pr code | …

fix(pascal): struggles with camel-cased strings

---

.github/workflows/publish-docs.yml
scripts/docs/ci-publish-docs.ts
scripts/docs/package.json
scripts/docs/pnpm-lock.yaml

This PR has a 3 goals:
1. When a tag is pushed to `radashi-org/radashi`, publish a new version of the docs. One exception to this is when a beta version only contains patches that did not change anything in the `docs/` folder.
2. Host multiple versions of the docs: one for the current stable version, one for the most recent beta version, one for the most recent alpha version (backed by the `next` branch, so breaking changes only), and finally the last two major versions before the current one. Old versions of the docs are phased out automatically. Only stable versions are published to the root directory. Others must have the "release ID" (e.g. `v12.2-beta`) in the URL.
3. Keep a `versions.json` file that includes all currently published versions of the docs, so we can provide a dropdown …

chore: add publish-docs workflow

---

src/curry/memo.ts
src/types.ts
tests/curry/memo.test-d.ts

> [!TIP]
Avoid inferring the `memo` return type from any of the given options, like the `key` callback.
See the added type tests for two examples.
Closes #230
No

fix(types): avoid inferring `memo` return type from `key` option

---

.devcontainer/devcontainer.json
.vscode/extensions.json
package.json
pnpm-lock.yaml

> [!TIP]
Recently, I noticed some activity in this [repository](https://github.com/radashi-org/radashi-tools/tree/master/packages/radashi-helper). I immediately wanted to set up the project so that these tools come pre-installed.
No

chore: use `radashi-helper`

---

renovate.json
scripts/format/format.ts

> [!TIP]
Create the config file to integrate the project with [renovate](https://docs.renovatebot.com/).
- Configured to run weekly on the weekend,
- All dependencies will be grouped in a single PR.
- Use the [dependency dashboard](https://docs.renovatebot.com/configuration-options/#dependencydashboard) in the issue.
https://github.com/orgs/radashi-org/discussions/170
No

ci: config renovate config file

---

benchmarks/array/merge.bench.ts
src/array/merge.ts

Changed the `array.indexOf` to Map to get rid of the nested loop and make the function work faster with large arrays. The function performs a slight worse for the small arrays, but the difference is negligible. With a big arrays it's significantly faster. The benchmark shows that for arrays with 10000 elements the new implementation is 10 times faster.
No
| M | `src/array/merge.ts` | 210 | +25 (+14%) |

chore: make merge function work faster with large arrays

---

package.json
pnpm-lock.yaml
vitest.config.ts

> [!TIP]
Fix Vitest `typecheck` by (1) updating Vitest (2) enabling `typecheck` (3) pointing typecheck to the tests tsconfig
All 3 avenues must be applied together, omitting one causes `type-d.ts` files either to pass blindly (false negatives) or not report at all.
Closes #244 
No
| M | `src/array/merge.ts` | 185 | -25 (-12%) |

fix: vitest `typecheck`

---

tests/typed/isEqual.test.ts

This PR adds 2 already succeeding test cases for Javascript Sets and Maps to further ensure that `isEqual` works as expected. The test cases assure that Maps and Sets are compared agnostic of insertion order.
[Adding testcases for Sets and Maps agnostic of insertion order](https://github.com/radashi-org/radashi/issues/268)
No
I'm currently NOT running on a linux machine and cannot run the linting due to the bash dependecy. I will try to install wsl soon but wont be able to do it now.

test(isEqual): add order-agnostic cases for Set and Map

---

src/object/omit.ts
tests/object/omit.test.ts

> [!TIP]
This pull request is an enhancement to the omit function, allowing it to accept `readonly` array keys. This means that the keys array cannot be modified within the function
https://github.com/radashi-org/radashi/issues/267
No

feat(types): allow readonly array in `omit` function

---

v12.2.0.md

The release notes for v12.2.0, a work in progress. I've created a `release-notes` branch, which this PR targets, so I could open a PR tracking my progress and inviting collaboration. This should help keep the process open and transparent. These release notes will also exist in the GitHub Releases section upon completion.
What's needed:
- ~More/better code examples~ (edit: Now that we link to the docs, this isn't as big of a deal. Just make sure the example previews the core functionality.)
- Check for missing commits (excluding `chore` commits)
- Ensure all PR/commit links are inside the headings
- General proof-reading and refinement
I used [this script](https://github.com/radashi-org/radashi/tree/main/scripts/release-notes) to generate the initial draft. The generated draft saved a lot …

chore: add v12.2.0 release notes

---

src/object/shake.ts
tests/object/shake.test-d.ts

> [!TIP]
When no `filter` argument is passed to `shake`, we can narrow property types to exclude undefined. Notably, optionality of properties (i.e. `foo?: string`) must not be affected, since `shake` does not guarantee the existence of any property; it only guarantees that a *defined* property does not have an `undefined` value (oh JavaScript, you absolute mad lad).
[This issue](https://github.com/sodiray/radash/issues/388) inspired me to take a closer look at our version of `shake`, so you could say it's fixed by this PR.
No

fix(types): improve signature of `shake`

---

src/object/mapValues.ts
tests/object/mapValues.test-d.ts

> [!TIP]
`mapValues` was incorrectly handling index signatures at the type level:
```ts
// BEFORE
const object = mapValues({} as { [key: string]: number }, x => String(x))
//    ^? { [key: string]: string; [key: number]: string }
// AFTER
const object = mapValues({} as { [key: string]: number }, x => String(x))
//    ^? { [key: string]: string }
```
No

fix(types): `mapValues` index signature handling

---

src/array/zipToObject.ts
tests/array/zipToObject.test-d.ts

> [!TIP]
The zipToObject function did not work with readonly/const arrays
#288
No

fix(types): let `zipToObject` receive readonly arrays

---

src/async/AggregateError.ts
tests/async/AggregateError.test.ts
tests/async/all.test.ts
tests/async/parallel.test.ts
tests/tsconfig.json

> [!TIP]
JSR doesn't allow a package to be published if it contains a triple-slash reference directive.
Evidenced by output of `pnpm lint jsr`:
```
[jsr] Checking for slow types in the public API...
[jsr] error[banned-triple-slash-directives]: triple slash directives that modify globals are not allowed
[jsr]  --> /Users/alec/dev/oss/radashi/src/async/AggregateError.ts:1:1
[jsr]   | 
[jsr] 1 | /// <reference lib="es2021.promise" />
[jsr]   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the triple slash directive
[jsr]   | 
[jsr]   = hint: remove the triple slash directive
[jsr] 
[jsr]   info: instead instruct the user of your …
```

chore: avoid triple-slash reference directive

---

docs/typed/isEmpty.mdx
src/typed/isEmpty.ts
tests/typed/isEmpty.test-d.ts
tests/typed/isEmpty.test.ts

> [!TIP]
Improve types with type guards.  
Now, anyone using the function will have enhanced type safety.
I don't know if the documentation is needed, But I did this more with people in mind who don't have knowledge of TypeScript's Type Guards. 
- https://github.com/orgs/radashi-org/discussions/209
- https://github.com/sodiray/radash/issues/422
No

fix(types): improve `isEmpty` signature

---

.github/next-minor.md
src/array/first.ts
src/array/last.ts
tests/array/first.test-d.ts
tests/array/last.test-d.ts

As with `draw()` in #153, we can narrow the return type for `first()` and `last()` in case the argument is known to be empty or non-empty.
With custom `defaultValue`:
- Related: #153
- Previous attempt: #140 
No
_Calculating..._

fix(types): narrow return type of `first` and `last`

---

src/random/draw.ts
tests/random/draw.test-d.ts

This is a renewed attempt at narrowing the return type for `draw()`, so that emptiness of the array argument is taken into account.
- For literal array arguments, return type can be determined as `T` or `null`.
- For mutable array arguments, return type remains `T|null`.
- For immutable array arguments, 
- return type remains `T|null` for empty arrays (not sure why)
- return type is narrowed to `T` for non-empty arrays.
---
Disclosure: I am a Typescript novice and welcome your feedback.
If the approach is sound, similar overrides could be considered for
- `first`
- `last`
- Previous attempt: #139 
No

fix(types): improve `draw` signature for non-empty arrays

---

src/async/all.ts
tests/async/all.test-d.ts

> [!TIP]
Make `all` less strict both at the type level and at runtime, making it closer to `Promise.all` behavior.
1. Values are not required to have a `then` method (e.g. promises and promise-like objects). If no `then` method exists, the value is used as-is.
2. I've made the following performance improvements:
- Avoid heap allocations where possible. Previously, `all` would create one array per promise when called with an array of promises. In all cases, `all` would create an additional object upon the resolution of each promise. Upon completion, `all` would filter the results, which allocated another array, and map …

fix(all): be more lenient, reduce memory usage

---

.github/next-minor.md
docs/async/parallel.mdx
docs/async/retry.mdx
src/async/parallel.ts
src/async/retry.ts
tests/async/parallel.test.ts
tests/async/retry.test.ts
tsconfig.json

> [!TIP]
This PR adds an option to pass `AbortController.signal` to `retry` and `parallel` to end their execution before looping over all of the array items, or going through all of the retry attempts. When aborted, the functions throw an `Error` with the message `Operation aborted`.
```ts
// _.retry
import * as _ from 'radashi'
const abortController = new AbortController()
const signal = abortController.signal
const promise = _.retry({ times: 3, delay: 1000, signal }, api.users.list)
// To abort the operation:
abortController.abort()
try {
await promise
} catch (err) {
if (err.message === 'Operation aborted') { …
```

feat: add `signal` option to `retry` and `parallel`

---

renovate.json

Due to a large amount of updates, in the [dependency update PR](https://github.com/radashi-org/radashi/pull/282), I think it makes sense to configure the dependency bot to only recommend [updating dependencies that are more than 30](https://docs.renovatebot.com/configuration-options/#minimumreleaseage) days old and that have a [high level of confidence.](https://docs.renovatebot.com/merge-confidence/#confidence-levels-and-their-meaning)
No

chore(renovate): be more conservative with dependency upgrades

---

.github/next-minor.md
benchmarks/typed/isUndefined.bench.ts
docs/typed/isUndefined.mdx
src/mod.ts
src/typed/isUndefined.ts
tests/typed/isUndefined.test.ts

> [!TIP]
The PR adds the `isUndefined()` function to easily check if the passed in value is `undefined`.
https://github.com/orgs/radashi-org/discussions/303
No
| A | `src/typed/isUndefined.ts` | 60 |

feat: add `isUndefined` function

---

.github/next-minor.md
docs/async/parallel.mdx
src/async/parallel.ts
tests/async/parallel.test.ts

> [!TIP]
now: 
```ts 
const array = [1, 2, 3]
const doSomething = async (n: number) => { ...}
_.parallel(-1, array, doSomething) // run 1 function in paraller (in the current implementation no function is executed)
_.parallel(0, array, doSomething) // run 1 function in paraller (in the current implementation no function is executed)
_.parallel(100, array, doSomething) // run 3 function in paraller 
_.parallel(Infinity, array, doSomething) // run 3 function in paraller (in the current implementation this throws an error)
```
https://github.com/orgs/radashi-org/discussions/235
https://github.com/sodiray/radash/issues/426 …

feat(parallel): clamp the limit between 1 and array length

---

docs/series/series.mdx

> [!TIP]
The documentation for `series` contains a typo ("let's" instead of "lets") and has poor grammatical flow. This PR fixes it by making the documentation for the function more digestible.
No

docs: streamline `series` wording

---

src/async/parallel.ts
tests/async/parallel.test.ts

Passing an empty array to `parallel` resulted in a clamp [range error](https://github.com/radashi-org/radashi/blob/3426478b22002dd0c2ad3cd29c7602cc3f7d17a0/src/number/clamp.ts#L27).
Fixes #336
No
| M | `src/async/parallel.ts` | 1723 | +25 (+1%) |

fix(parallel): avoid range error with empty array

---

src/random/shuffle.ts

A bias observed while using the `shuffle` function led me to double-check the implementation.
I believe the current version of `shuffle` does not implement Fisher-Yates correctly, since it is picking random indices from the entire array length in the loop. 
The proper Fisher-Yates algorithm should only pick from the _unshuffled_ portion.
I am not a cryptographic analyst, but intuitively, picking random indices from the entire array length (rather than just the unshuffled portion) introduces statistical bias and breaks the randomness guarantee. Iterations can swap with any position, including ones we just shuffled, so we might "undo" or "re-shuffle" already shuffled elements.
No.
| M | `src/random/shuffle.ts` | 190 | …

fix(shuffle): correction to Fisher-Yates implementation

---

.github/next-major.md
docs/curry/debounce.mdx
src/curry/debounce.ts
tests/curry/debounce.test.ts

> [!TIP]
- Continue debouncing (in future calls) after `cancel` is called. Previously, `cancel` would disable debouncing, so future calls would be immediate.
- Do not have `flush` call the underlying function if no call is pending.
- Expose a reference to the underlying function with the new `callee` property.
Resolves #105
Resolves https://github.com/sodiray/radash/issues/362
Yes
| M | `src/curry/debounce.ts` | 257 | +9 (+4%) |

feat!: rework `debounce` function

---

.github/next-major.md
docs/typed/isNumber.mdx
src/typed/isFloat.ts
src/typed/isNumber.ts
tests/typed/isNumber.test.ts

> [!TIP]
This PR updates the `isNumber` function to return true for `NaN` values, Resolve #74 
https://github.com/sodiray/radash/issues/405
https://github.com/orgs/radashi-org/discussions/74
Yes
| M | `src/curry/debounce.ts` | 257 | +9 (+4%) |
| M | `src/typed/isNumber.ts` | 63 | -18 (-22%) |

fix(isNumber)!: return true for NaN values

---

src/async/reduce.ts
tests/async/reduce.test.ts

Optimizations include:
- Avoid using `array.entries()` which allocates one array per index unnecessarily
- Avoid using `array.slice(1)` when no initial value is provided
- To achieve the above cases, use `array.keys()` and call its `next()` method if the first element is used as the initial value
Other improvements in this commit:
- Align the “empty array with no initial value” error message with `Array.prototype.reduce`
- Use `arguments.length` to properly check whether an initial value was passed
Closes #340
No
| M | `src/async/reduce.ts` | 249 | +19 (+8%) |

fix(reduce): align with native reduce behavior + perf improvements

---

.github/next-minor.md
benchmarks/typed/isAsyncIterable.bench.ts
docs/typed/isAsyncIterable.mdx
src/mod.ts
src/typed/isAsyncIterable.ts
tests/typed/isAsyncIterable.test.ts

This PR adds the `isAsyncIterable` function to the `async` group.
This function checks if a value is an async iterable.
https://github.com/orgs/radashi-org/discussions/46
No
| A | `src/typed/isAsyncIterable.ts` | 162 |

feat: add isAsyncIterable function

---

.github/next-minor.md
docs/async/toResult.mdx
src/async/toResult.ts
src/mod.ts
tests/async/toResult.test.ts

This PR implements the `toResult` function in the async group. It converts a `PromiseLike` to a `Promise<Result>`.
N/A
No
| A | `src/async/toResult.ts` | 217 |

feat: implement toResult function

---

src/curry/debounce.ts

The `flush` method had an outdated signature. This error was introduced in #107.
No

fix(types): debounce `flush` method takes no arguments

---

.github/next-major.md
benchmarks/array/cluster.bench.ts
docs/array/cluster.mdx
src/array/cluster.ts
tests/array/cluster.test.ts

This PR removes the default size from the `cluster` function.
https://github.com/orgs/radashi-org/discussions/91
Yes
The `size` parameter is now required when calling the `cluster` function. Existing applications will need to provide a `size` argument when calling the function.
| M | `src/array/cluster.ts` | 107 | -2 (-2%) |
| M | `src/async/reduce.ts` | 239 | +10 (+4%) |
| M | `src/string/trim.ts` | 135 | +4 (+3%) |
| M | `src/typed/isEmpty.ts` | 475 | +113 (+31%) |

feat!: remove default size from `cluster`

---

src/number/range.ts

The `i <= final` can achieve normal exit from the loop, and there should be no need to `break` in the loop.
Yes
| M | `src/number/range.ts` | 156 | -14 (-8%) |

refactor(range): remove unnecessary break statement in range generator

---

src/array/mapify.ts
tests/array/mapify.test.ts

`index` is the index of the current item in the array in the [doc](https://radashi.js.org/reference/array/mapify/)
But using `map.size` as the index, if the ids are equal, it may not be consistent with expectations.
```ts
for (const item of array) {
map.set(getKey(item, map.size), getValue(item, map.size))
}
```
Yes
| M | `src/array/mapify.ts` | 115 | +2 (+2%) |

fix(mapify): modify the loop to use array indexes

---

src/array/objectify.ts
tests/array/objectify.test.ts

`objectify` will return `{}` when the array is `[]`. So, `Partial<Record<Key, Value>>` is more suitable
Yes

fix(objectify)!: wrap return type with Partial

---

src/array/selectFirst.ts
tests/array/selectFirst.test-d.ts

Adds type overloads to ensure selectFirst returns NonNullable<U> | undefined when no condition is provided, aligning behavior with nullish filtering.
Fixes: `selectFirst` return type doesn't filter out `null` type when `condition` parameter is undefined #411
Adds type overloads to ensure selectFirst returns NonNullable<U> | undefined when no condition is provided, aligning behavior with nullish filtering.
Fixes: `selectFirst` return type doesn't filter out `null` type when `condition` parameter is undefined #411
No

fix(selectFirst): correct return type when condition is undefined (#411)

---

.github/next-minor.md
benchmarks/oop/QuantityParser.bench.ts
docs/number/parseDuration.mdx
docs/number/parseQuantity.mdx
src/mod.ts
src/number/parseDuration.ts
src/number/parseQuantity.ts
src/oop/DurationParser.ts
src/oop/QuantityParser.ts
tests/oop/DurationParser.test.ts
tests/oop/QuantityParser.test.ts

Follow-up to #332 (thanks to @hugo082 for his preliminary work).
Differences from that PR include:
- Rename `parseHumanDuration` to `parseDuration`
- Changed `parseDuration` to accept only a string argument (no numbers)
- *This was done to keep the implementation lean.*
- Added the `QuantityParser` and `DurationParser` classes
- *The base QuantityParser class allows for custom parsers to be implemented easily and efficiently; while the DurationParser class is a subclass used by `parseDuration`.*
- Added `parseQuantity` function
https://github.com/orgs/radashi-org/discussions/150#discussioncomment-10865928
No
| A | `src/number/parseDuration.ts` | 820 |
| A | `src/number/parseQuantity.ts` | 525 |
| A | `src/oop/DurationParser.ts` | 780 | …

feat: add `parseDuration` and `parseQuantity` functions

---

src/curry/memo.ts
src/types.ts

> [!TIP]
- Expose the `memo` cache as a `cache` option. This allows the memo cache to be managed externally.
- Introduce the `Memoized<T>` type where `T is (...args: any) => any`.
- Remove the internal `memoize` function.
- `memo` only has one type parameter now, and it's a function type
- The `MemoOptions` type only has one type parameter now (same as `memo`)
Yes
| M | `src/curry/memo.ts` | 278 | -29 (-9%) |

feat(memo)!: add `cache` option

---

docs/async/promiseMemo.mdx
src/async/promiseMemo.ts
src/mod.ts
tests/async/promiseMemo.test.ts

Create a new function `promiseMemo`, it takes an asynchronus function as an argument, and memoize the result.
#381 
No
| A | `src/async/promiseMemo.ts` | 312 |

feat: add `promiseMemo` function
